[[redirects]]
    from = "/api/*"
    to = "/.netlify/functions/app/:splat"
    status = 200

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200

[build]
    functions = "functions"

[build.environment]
    NODE_VERSION = "20"